### ISSUE TITLE
What are the limitations of controlling thru RS485?

### ISSUE THREAD

**Issue by lukescott** [ronisaacson/cz2#2]
Before I get too far into this, what can I do with this, and what can I not do? Can I fully control and monitor my HVAC system? How does this interact with the XL1050? Does the XL1050 try to override commands, or does it see the changes as the "set temperature"?

**Comment by ronisaacson** [comment]
Hi Luke, what panel do you have? This library is for controlling the old ComfortZone II. The panel looks like [this](https://s.ecrater.com/stores/59531/586f07e640d02_59531b.jpg) and the master thermostat looks like [this](https://cdn.shopify.com/s/files/1/2139/8037/products/115CarrierZONECC0USISA-B_2_1024x1024.jpg). There are no other compatible thermostats with this panel. If you have a panel that works with the XL1050, it's probably a newer one that uses a different protocol.

**Comment by lukescott** [comment]
Hey Ron.. I don't have it yet. I'm having a new HVAC system installed next week (to replace a 15yr old system). Specifically installing the XV20i and XC80 combo. On the product page it says "ComfortLink II communicating capability" (which I just now realized is not Comfort Zone II - similar naming).

The reason I'm looking into this it the XL1050 is a ZWave controller and doesn't allow control thru ZWave (so I can't control HVAC thru ZWave using my home automation system). And as far as I know, the XL1050 is the only thermostat compatible with the variable inverter (vs 2 stage). Trying to find some way to monitor and control the system locally without having to go thru a server (as my whole system is locally controlled).

My only other option was to go with a 2 stage system, which lets me use the XL624. But then I lose out on the variable tech (which can run at 30% to 100% at 55dbA to 75dbA verses 70% to 100% at 74dbA to 75dbA; looking for quiet and efficient).

**Comment by ronisaacson** [comment]
Ah yes, the ComfortLink II and ComfortZone II are totally unrelated. The ComfortZone II supported by this library is an obsolete line of equipment from the early 2000s. It uses a proprietary protocol and there's no wifi- or automation-capable thermostat which supports it, but some of us have managed to get together and reverse engineer the serial protocol. That's what this library is for, to add remote-control capability to this old panel because there's no other way to get it.

For the newer equipment you're talking about, I'm afraid I'm not familiar with it. You might check out the [infinitive](https://github.com/acd/infinitive) and [infinitude](https://github.com/nebulous/infinitude) projects which do something similar with the newer Carrier Infinity protocol. I think the ComfortLink II might support the Infinity protocol but I'm not positive.

**Comment by lukescott** [comment]
The system is installed. I haven't had much of a chance to dig into the CL protocol let. The names are so similar I got them mixed up. Thank you for pointing that out to me.
